### ISSUE TITLE
MFRC522 Hexadecimal input

### ISSUE THREAD

**Issue by sohailahmadsgd** [BiTinerary/OrangePiZeroMFRC522#3]
Hi
I am working on a project and want to enter Hexadecimal values for input data rather than ACII.
I am really new to RPi and also to Python. I dont know where to ask and how to get help.
Can someone help me with this

**Comment by BiTinerary** [comment]
I'll take you under my wing. I've been working with python and SBC's for years, still consider myself a newb like you. The past 5 years of this newbs life was forever changed by a 30 minute lunch break, crash course into python.

The repo you're posting this to isn't valid. I'm currently ****ing with it in order to make it more simple. If you have any questions, feel free to ask and inquire. As far as hex/ascii relative to python, look into base functions here:

https://stackoverflow.com/questions/8088375/how-do-i-convert-a-single-character-into-its-hex-ascii-value-in-python

**Comment by sohailahmadsgd** [comment]
Thanks a lot
It was really helpful. I fixed the problem
You are awesome.
